CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(1000) NOT NULL
);

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(1000) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE TABLE TBL_PRODUCT_ORDER(
	ID NUMBER CONSTRAINT PK_PRODUCT_ORDER PRIMARY KEY,
	ORDER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	CONSTRAINT FK_PRODUCT_ORDER_ORDER FOREIGN KEY(ORDER_ID)
	REFERENCES TBL_ORDER(ID),
	CONSTRAINT FK_PRODUCT_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)	
);

CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE TABLE TBL_PAY(
	ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
	ORDER_ID NUMBER NOT NULL,
	CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
	REFERENCES TBL_ORDER(ID)
);





