CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_BIRTH DATE NOT NULL,
	MEMBER_PHONE VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(500) NOT NULL
);

SELECT * FROM TBL_MEMBER;