CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	MEMBER_ID NUMBER NOT NULL,
	POST_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_REPLY;