CREATE SEQUENCE SEQ_FILE;

CREATE TABLE TBL_FILE(
	ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_PATH VARCHAR2(1000) NOT NULL,
	FILE_UUID VARCHAR2(1000) NOT NULL,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	POST_ID NUMBER NOT NULL,
	CONSTRAINT FK_FILE_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);

ALTER TABLE TBL_FILE ADD (FILE_TYPE VARCHAR2(500));

SELECT * FROM TBL_FILE;
