CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	MEMBER_ID NUMBER NOT NULL,
	POST_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_REPLY;

INSERT INTO TBL_REPLY
(ID, REPLY_CONTENT, MEMBER_ID, POST_ID)
VALUES(SEQ_REPLY.NEXTVAL, '댓글 내용 테스트5', 21, 22);




SELECT ID, REPLY_CONTENT, REPLY_REGISTER_DATE, REPLY_UPDATE_DATE, MEMBER_ID, MEMBER_NAME, POST_ID
        FROM
        (
            SELECT ROWNUM R, RE.ID, REPLY_CONTENT, REPLY_REGISTER_DATE, REPLY_UPDATE_DATE, RE.MEMBER_ID, MEMBER_NAME, POST_ID
            FROM
            (
                SELECT RE.ID, REPLY_CONTENT, REPLY_REGISTER_DATE, REPLY_UPDATE_DATE, RE.MEMBER_ID, MEMBER_NAME, POST_ID
                FROM TBL_MEMBER M JOIN TBL_REPLY RE
                ON POST_ID = 22 AND M.ID = RE.MEMBER_ID
                ORDER BY RE.ID DESC
            ) RE
            WHERE
                ROWNUM <= 11
        )
        WHERE R > 0;



